###### What is Numpy?
Numpy is a fundamental library for numerical computations in Python. It provides support for arrays, matrices, and many mathematical functions.

###### Installing Numpy:
To install Numpy, use the following command:
pip install numpy


###### Importing Numpy:
To use Numpy in your code, import it as follows:
import numpy as np


In [6]:
import numpy as np

# Creating numpy arrays:
You can create arrays using np.array() function and also using many other functions

In [2]:
arr = np.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]


In [4]:
# Integer array
int_arr = np.array([1, 2, 3], dtype='int')
print("Integer array:", int_arr)

# Float array
float_arr = np.array([1, 2, 3], dtype='float')
print("Float array:", float_arr)

# Complex array
complex_arr = np.array([1, 2, 3], dtype='complex')
print("Complex array:", complex_arr)


Integer array: [1 2 3]
Float array: [1. 2. 3.]
Complex array: [1.+0.j 2.+0.j 3.+0.j]


In [5]:
# 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array:\n", arr_2d)

# 3D array
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D array:\n", arr_3d)


2D array:
 [[1 2 3]
 [4 5 6]]
3D array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [3]:
zeros_arr = np.zeros((2, 3))
print("Zeros array:\n", zeros_arr)
ones_arr = np.ones((2, 3))
print("Ones array:\n", ones_arr)
empty_arr = np.empty((2, 3))
print("Empty array:\n", empty_arr)


Zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones array:
 [[1. 1. 1.]
 [1. 1. 1.]]
Empty array:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [7]:
range_arr = np.arange(0, 10, 2)  # Start, stop, step
print("Range array:", range_arr)


Range array: [0 2 4 6 8]


In [8]:
linspace_arr = np.linspace(0, 1, 5)  # Start, stop, number of points
print("Linearly spaced array:", linspace_arr)


Linearly spaced array: [0.   0.25 0.5  0.75 1.  ]


In [11]:
identity_matrix = np.eye(3)  # 3x3 identity matrix
print("Identity matrix:\n", identity_matrix)


Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
diagonal_matrix = np.diag([1, 2, 3])
print("Diagonal matrix:\n", diagonal_matrix)


Diagonal matrix:
 [[1 0 0]
 [0 2 0]
 [0 0 3]]


In [10]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape((2, 3))
print("Reshaped array:\n", reshaped_arr)
arr=np.array([[1,2],[3,4],[5,6]])
reshaped_arr = arr.reshape((1,6))
reshaped_arr

Reshaped array:
 [[1 2 3]
 [4 5 6]]


array([[1, 2, 3, 4, 5, 6]])

In [14]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
flattened_arr = arr_2d.flatten()
print("Flattened array:", flattened_arr)


Flattened array: [1 2 3 4 5 6]


# Numpy Array Properties


In [15]:
import numpy as np

### Numpy Array Properties

# Create a sample array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# 1. Shape
print("Shape:", arr.shape)
# Output: Shape: (2, 3)

# 2. Size
print("Size:", arr.size)
# Output: Size: 6

# 3. Number of dimensions (ndim)
print("Number of dimensions:", arr.ndim)
# Output: Number of dimensions: 2

# 4. Data type (dtype)
print("Data type:", arr.dtype)
# Output: Data type: int64

# 5. Item size (itemsize)
print("Item size:", arr.itemsize)
# Output: Item size: 8

# 6. Total bytes consumed by the elements (nbytes)
print("Total bytes:", arr.nbytes)
# Output: Total bytes: 48

# 7. Transpose (T)
print("Transposed array:\n", arr.T)
# Output: 
# Transposed array:
# [[1 4]
#  [2 5]
#  [3 6]]

# 8. Flat (flat)
print("Flat array:", list(arr.flat))
# Output: Flat array: [1, 2, 3, 4, 5, 6]

# Create a complex array
complex_arr = np.array([1+2j, 3+4j, 5+6j])

# 9. Real part (real)
print("Real part:", complex_arr.real)
# Output: Real part: [1. 3. 5.]

# 10. Imaginary part (imag)
print("Imaginary part:", complex_arr.imag)
# Output: Imaginary part: [2. 4. 6.]



Shape: (2, 3)
Size: 6
Number of dimensions: 2
Data type: int32
Item size: 4
Total bytes: 24
Transposed array:
 [[1 4]
 [2 5]
 [3 6]]
Flat array: [1, 2, 3, 4, 5, 6]
Real part: [1. 3. 5.]
Imaginary part: [2. 4. 6.]


# Basic Array Operations


In [16]:
#indexing and slicing-1D Arrays
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])    # First element
print(arr[1:4])  # Elements from index 1 to 3


1
[2 3 4]


In [18]:
#indexing and slicing-2D Arrays
arr = np.array([1, 2, 3, 4, 5,6,7,8]).reshape((2,4))
print(arr[0,1])#second element in first row
print(arr[0,:])#first row
print(arr[:,1])#second column
print(arr[0,::2])#first row values with step count 2
print(arr[::-1,::-1])#revefrse by row first and then reverse by column 

2
[1 2 3 4]
[2 6]
[1 3]
[[8 7 6 5]
 [4 3 2 1]]


In [17]:
#Reshaping
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape((2, 3))
print(reshaped_arr)


[[1 2 3]
 [4 5 6]]


In [20]:
#Concatenate -same dimensions
arr=np.array([[11,12],[23,45]])
arr1=np.array([[17,18],[34,56]])
res=np.concatenate([arr,arr1])
res1=np.concatenate([arr,arr1],axis=1)
res2=np.hstack([arr,arr1])
print(res)
print(res1)
print(res2)

[[11 12]
 [23 45]
 [17 18]
 [34 56]]
[[11 12 17 18]
 [23 45 34 56]]
[[11 12 17 18]
 [23 45 34 56]]


In [36]:
#Concatenate -diff dimensions(1D and 2D)
arr=np.array([1,2,3])
arr1=np.array([[4,5,6],[7,8,9]])
res=np.vstack([arr,arr1])
print(res)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [23]:
#Split-1D
arr=np.array([1,2,3,4,5,6,7,8,9])
x1,x2,x3=np.split(arr,[3,6])
print(x1)
print(x2)
print(x3)

[1 2 3]
[4 5 6]
[7 8 9]


In [25]:
#Split-2D-vertical
arr=np.arange(9).reshape([3,3])
x1,x2=np.vsplit(arr,[1])
print(x1)
print(x2)

[[0 1 2]]
[[3 4 5]
 [6 7 8]]


In [26]:
#Split-2D-horizontal
arr=np.arange(9).reshape([3,3])
x1,x2=np.hsplit(arr,[1])
print(x1)
print(x2)

[[0]
 [3]
 [6]]
[[1 2]
 [4 5]
 [7 8]]


# Universal functions
The key to make computations fast in NumPy Array is to use vectorized operations, generally implemented through Num‐
Py’s universal functions (ufuncs).

In [31]:
#Array arithmetic
x = np.arange(4)
print("x =", x)
print("x + 5 =", x + 5)#np.add(x,5)
print("x - 5 =", x - 5)#np.subtract(x,5)
print("x * 2 =", x * 2)#np.multiply(x,5)
print("x + 5 =", x /5)#np.divide(x,5)
print("x - 5 =", x // 5)#np.floor_divide(x,5)
print("x * 2 =", x **2)#np.power(x,2)
print("x * 2 =", x %2)#np.mod(x,2)
print("-x=",-x)#np.negative(x)
#np.abs(x) and np.absolute(x)

x = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x + 5 = [0.  0.2 0.4 0.6]
x - 5 = [0 0 0 0]
x * 2 = [0 1 4 9]
x * 2 = [0 1 0 1]
-x= [ 0 -1 -2 -3]


In [32]:
#trignometric functions
theta = np.linspace(0, np.pi, 3)
print("theta = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))


theta =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [33]:
#Exponents and logarithms
x = [1, 2, 3]
print("x =", x)
print("e^x =", np.exp(x))
print("2^x =", np.exp2(x))
 print("3^x =", np.power(3, x))
x = [1, 2, 4, 10]
print("x =", x)
print("ln(x) =", np.log(x))
print("log2(x) =", np.log2(x))
print("log10(x) =", np.log10(x))

x = [1, 2, 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
2^x = [2. 4. 8.]
3^x = [ 3  9 27]
x = [1, 2, 4, 10]
ln(x) = [0.         0.69314718 1.38629436 2.30258509]
log2(x) = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


# Aggregate Functions
NumPy has fast built-in aggregation functions for working on arrays.These aggregate functions are used to compute summary
statistics for the data

In [37]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

107 ms ± 4.7 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.67 ms ± 45.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [35]:
%timeit min(big_array)
%timeit np.min(big_array)

67 ms ± 5.13 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
617 µs ± 12.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
